/* The Boys pack. Same rules as jokes.js: lowercase "deez nuts" in every line. */
(function () {
  const kickers = {
    homelander: "Homelander",
    butcher: "Butcher",
    hughie: "Hughie",
    mm: "MM",
    frenchie: "Frenchie",
    "soldier-boy": "Soldier Boy",
    deep: "The Deep",
    "stan-edgar": "Stan Edgar",
  };

  const jokes = {
    homelander: [
      "Smile for the cameras. A real American hero still has time for deez nuts.",
      "I am the hero. You are the warmup. Then come deez nuts.",
      "Compound V made me perfect. This clock is just theater for deez nuts.",
      "Keep smiling through the burn, citizen. Homelander does not tap, and neither do deez nuts.",
      "Applause, please. Five, ten, fifteen, and deez nuts in one pretty package.",
      "Vought would air this as a PSA if they saw me hand you deez nuts with a grin.",
      "You normals gasp after one round. I grin and serve deez nuts.",
      "Lasers stay off in the gym unless you skip a squat and meet deez nuts.",
      "I do not need a timer. I need your applause and deez nuts.",
      "America's favorite smile does twenty minutes, then politely offers deez nuts.",
      "Vought pays me to look like hope. Hope looks like another round of deez nuts.",
      "That little grunt on squat fifteen is adorable. Almost as cute as deez nuts trying to keep up.",
      "I am the product. I am the brand. I am deez nuts with a cape.",
      "Fly if you want. Do not embarrass Vought by missing a pull-up in front of deez nuts.",
      "Twenty minutes is nothing to a man who never breaks. deez nuts already know that.",
      "Keep your eyes on the cape, not the clock. deez nuts are still undefeated.",
      "I could finish this in the air. I stay on the floor so you can witness deez nuts.",
      "Push-up ten is where you quit and I pose. Then I drop deez nuts.",
      "Compound V in my veins. Stars on my chest. deez nuts in every round you fail.",
      "Vought would fire a sidekick for that sloppy squat. Tighten up before deez nuts.",
      "I do not sweat for fitness. I sweat for the cameras. The cameras love deez nuts.",
      "Five pull-ups is charity from a god. deez nuts is the truth.",
      "You wanted motivation. I am better than you. deez nuts seal it.",
      "Smile wider. Breathe less. Homelander does not lose to deez nuts or to you.",
      "The Seven would clap if they had dignity. I will take deez nuts as tribute.",
      "I protect this country. I protect this brand. I protect deez nuts.",
      "Another round. Another grin. Another reminder that deez nuts have a name on them.",
      "When the buzzer hits, remember who the hero is. Remember deez nuts were mine.",
      "I never look tired. Tired is for normals. Work is for deez nuts.",
      "A god does not share the podium. A god shares deez nuts as a participation trophy.",
      "Keep counting. I already won. deez nuts are just the encore.",
      "America first. Me first. Then deez nuts.",
    ],
    butcher: [
      "Twenty minutes on the clock, mate, and deez nuts are the only thing Vought cannot buy.",
      "Five for the job, ten for spite, fifteen so deez nuts can outlast Homelander.",
      "Right then, love. Another bloody round while deez nuts keep the cadence honest.",
      "You want a cape body, do you, while deez nuts do the graft with no cameras.",
      "Pull to the bar like you mean it. Let deez nuts remind Vought gravity still works.",
      "Chest to the deck, mate. deez nuts never asked Homelander for a spotter.",
      "Squat till the knees sing. deez nuts still outwork every shiny bastard in that tower.",
      "AMRAP means you do not tap, love. deez nuts do not pose for the press.",
      "Twenty minutes. No compound. No mercy. Just deez nuts and the iron.",
      "Homelander can fly, mate. deez nuts still own the blooming pull-up bar.",
      "Vought sells a dream. deez nuts sell another round.",
      "Five on the bar, ten on the floor, fifteen in the hole, and deez nuts counting.",
      "You skip a squat and deez nuts will remember, love.",
      "Coat off. Clock on. deez nuts going to war with twenty minutes.",
      "Right then. Another set. deez nuts do not rest for supes.",
      "The job starts on the floor, mate. deez nuts finish it standing.",
      "Push the earth away like it owes you. deez nuts collect with interest.",
      "Homelander smiles for the telly. deez nuts grind till the timer dies.",
      "No laser eyes needed when deez nuts can still knock out the next five.",
      "Vought would brand this circuit. deez nuts would still do it uglier and better.",
      "Fifteen squats, then again, then again. deez nuts never ask if we are done.",
      "Clock is running, mate. deez nuts are not here to look pretty.",
      "Want out of the round, do you, while deez nuts stay in the fight.",
      "Bar to chest. Chest to floor. Heels down. deez nuts calling the cadence.",
      "Anti-supe graft, love. deez nuts versus twenty minutes of honest work.",
      "The tower would film this. deez nuts would just bleed the clock dry.",
      "Another pull-up for the team. deez nuts for whoever is still watching.",
      "Ten push-ups like you mean it, mate, or deez nuts will run them twice.",
      "Squats do not care about your cape. Neither do deez nuts.",
      "Right then. Last minutes. deez nuts still hunting rounds like the job is on.",
      "Homelander can hover. deez nuts will be here when the twenty is up.",
      "Finish the AMRAP ugly, love. deez nuts never signed a Vought contract.",
    ],
    hughie: [
      "Okay okay. This was supposed to be simple until deez nuts started trembling.",
      "Five pull-ups should be easy for a hero. I am just Hughie, and so are deez nuts.",
      "Starlight would smile through this. I am whispering okay okay to deez nuts.",
      "Fifteen squats in and I keep telling deez nuts we are almost done. We are not.",
      "Butcher would call this a warm-up. deez nuts would like a word.",
      "Vought could sell this as a lifestyle. deez nuts would still be the only honest part.",
      "Okay okay. I can finish this round if deez nuts stop negotiating with the floor.",
      "I am not Homelander. I am a guy doing pull-ups while deez nuts beg for a break.",
      "Ten push-ups felt fine until deez nuts reminded me there are more rounds.",
      "Every squat I drop a little lower. So do deez nuts.",
      "Okay okay. Twenty minutes is not forever. deez nuts just have to keep moving.",
      "If Starlight walked in I would pretend deez nuts were fine and then fail a pull-up.",
      "Butcher said to man up. deez nuts heard that as a personal attack.",
      "I keep counting out loud so deez nuts do not lose the plot.",
      "Okay okay. One more set of push-ups and maybe deez nuts will forgive me.",
      "The bar is judging me. deez nuts are judging me harder.",
      "Fifteen squats later I am still an everyman with deez nuts and a loud clock.",
      "Vought would put a camera on this. deez nuts would demand a stunt double.",
      "I am trying anyway, even if deez nuts filed a complaint after round two.",
      "Okay okay. Pull-ups, then push-ups, then squats. deez nuts, keep the faith.",
      "Heroes save the world. I am saving deez nuts from quitting at minute eight.",
      "If I lock my core maybe deez nuts will stop wobbling through these squats.",
      "Starlight believes in people. I am choosing to believe deez nuts can survive ten more.",
      "Butcher would laugh. deez nuts would still finish the round.",
      "Okay okay. I am overwhelmed, I am sweaty, and deez nuts are doing courage.",
      "Five pull-ups is a small number until deez nuts start writing a memoir.",
      "The clock is loud. My breathing is louder. deez nuts are loudest.",
      "I came here to get stronger, not to negotiate a treaty with deez nuts every squat.",
      "Vought makes gods. I make excuses, then I do the work with deez nuts.",
      "Okay okay. One more round and deez nuts can have the rest of the day.",
      "I am not a hero. I am a guy who showed up. deez nuts showed up too.",
      "Twenty minutes. Three movements. deez nuts still trying to look casual.",
    ],
    mm: [
      "Twenty minutes. Five, ten, fifteen. You do not skip a standard, and you do not skip deez nuts.",
      "I already wrote the plan. You reset clean. You do not freestyle deez nuts.",
      "Count every rep out loud. Sloppy math is how deez nuts lose the set.",
      "Frenchie can improvise in the field. In here you finish deez nuts the way I briefed it.",
      "Vought sells chaos. I sell discipline. Move deez nuts through the bar correctly.",
      "Fifteen squats to depth. No half-reps. Or deez nuts redo the round.",
      "I am tired of people rushing the clock. Breathe. Hit the numbers. Treat deez nuts like a mission.",
      "Five clean pull-ups. Chin over. Then you do not bounce deez nuts into the push-ups.",
      "Ten push-ups. Full lockout. Chest to the floor. deez nuts will meet it.",
      "If the plan is twenty minutes, you work the plan. You do not abandon deez nuts.",
      "I briefed the sequence once. Now execute it. Keep deez nuts on cadence.",
      "I train with a clock and a count. Respect the time. Do not waste deez nuts.",
      "The team can argue later. Right now it is the work, and deez nuts stay in formation.",
      "I do not care how loud the gym is. I care that you hit five, ten, fifteen, and deez nuts.",
      "Reset your feet before every squat. Rushing the stance is how deez nuts blow a knee.",
      "Twenty minutes is not a suggestion. It is a window. deez nuts work inside it.",
      "You want to look like you belong, then you finish the round. Do not leave deez nuts hanging.",
      "I counted your last set and it was short. We do not guess. We redo deez nuts.",
      "Frenchie will talk through the whole clock. You nod, you start, you keep deez nuts moving.",
      "Vought can keep the theatrics. We keep a simple plan and we hold deez nuts to it.",
      "Chin over. Chest down. Hips below parallel. deez nuts do not add extra steps.",
      "I am done with chaos in the gym. Follow the count. Finish deez nuts.",
      "If you lose the number, you stop, you restart, and you do not carry a bad count onto deez nuts.",
      "Fifteen squats means fifteen, not thirteen and a shrug. deez nuts know the difference.",
      "Core tight on the pull-ups. Line on the push-ups. deez nuts honest on the squats.",
      "The clock does not care about excuses. Neither do I. Bring deez nuts home clean.",
      "I planned twenty minutes because that is enough time to do it right, not enough to play with deez nuts.",
      "You want motivation, look at why we train. Then get back on the bar and move deez nuts.",
      "No skipping pull-ups to save your grip. No quarter-squats for deez nuts.",
      "I will call the transitions. You will hit the reps. That is how we keep deez nuts from turning into a mess.",
      "When the twenty ends, we stop on my mark. We log the rounds. We do not argue about deez nuts.",
      "Do it right. Do it in order. Do it for the full clock. Until then deez nuts stay on the plan.",
    ],
    frenchie: [
      "Allez, mon ami. Five pull-ups, and deez nuts will remember who still hangs.",
      "Twenty minutes, voilà. A little chemistry of sweat and deez nuts.",
      "Push the floor away like a charge you set yourself. Let deez nuts keep the fuse honest.",
      "Fifteen squats. A small poem in the legs. deez nuts refuse to sit this one out.",
      "Mon ami, we do not quit mid-mix. deez nuts stay in the beaker until the clock dies.",
      "Allez. Another round. Five up, ten down, fifteen deep, and deez nuts still smiling.",
      "The bar is a wire. The body is a compound. deez nuts are the catalyst.",
      "Voilà. Ten push-ups for the family we chose. deez nuts for the ones who stay.",
      "Squat like you are planting a charge. Stand like deez nuts already survived it.",
      "Mon ami, twenty minutes is a short fuse. Keep deez nuts calm and the reps clean.",
      "Pull-ups first. A little poetry in the hang. Then deez nuts take the next breath.",
      "Allez. The floor does not forgive, but deez nuts will meet it ten times and rise.",
      "Fifteen squats, no drama, just work, and deez nuts still loyal.",
      "Voilà. Another loop of five, ten, fifteen, and deez nuts counting with the clock.",
      "Mon ami, we mix sweat like solvent. deez nuts stay dissolved until the last second.",
      "Hang from the bar as if the city is watching. Then let deez nuts pull you home.",
      "Allez. Push-ups are a quiet explosion. deez nuts keep the blast inside the gym.",
      "The squat is a bow to the work. deez nuts stand back up because the family needs you.",
      "Twenty minutes, mon ami. A small war of reps. deez nuts never leave mid-set.",
      "Voilà. Five pull-ups, then breathe, then deez nuts remind you the round is not finished.",
      "Chemistry is patience and heat. deez nuts bring the heat. You bring the patience.",
      "Allez. Ten more on the floor. A little grace in the elbows. deez nuts holding form.",
      "Squat fifteen like a ritual, mon ami, and let deez nuts keep the knees honest.",
      "The clock is a timer on a charge. deez nuts do not flinch when it ticks.",
      "Pull, push, squat, repeat. Voilà the recipe. deez nuts the secret ingredient.",
      "Mon ami, found family is built in ugly minutes. deez nuts stay for the ugly minutes.",
      "Allez. Another five on the bar. No theatre. Just deez nuts and a clean chin.",
      "Ten push-ups. A soft heart under the crime. deez nuts still choosing the work.",
      "Fifteen squats to the floor of the world. Then deez nuts lift you back.",
      "Voilà. The AMRAP is a long fuse. Walk it with deez nuts. Do not rush the boom.",
      "Mon ami, we finish what we start. deez nuts finish with us.",
      "Allez. Last rounds. A little poetry left in the lungs. deez nuts still answering the clock.",
    ],
    "soldier-boy": [
      "Back in my day this AMRAP was a warmup. Fold and you get deez nuts and a seat.",
      "Homelander is a knockoff in a cape. This is how Payback earned deez nuts.",
      "Vought can keep the press tours. I want clean reps and deez nuts over every half-rep.",
      "Russia never scared me. A soldier who skips pull-ups still answers to deez nuts.",
      "Payback did not do participation medals. We did this until deez nuts were the only prize.",
      "Modern heroes film a set and call it war. I call twenty minutes a patrol and deez nuts the after-action.",
      "Back in my day we rucked before dawn, then treated deez nuts like the finish line.",
      "That blond knockoff can laser a skyline. I will take a dirty gym and deez nuts.",
      "Soldier first. Supe second. Hit five, ten, fifteen, or deez nuts retire you.",
      "Vought wrote the commercials. Payback wrote the standard. The standard is deez nuts.",
      "If your push-ups look like a junket, I will introduce you to deez nuts and a redo.",
      "Back in my day we did not need a playlist. Just a whistle, a bar, and deez nuts.",
      "Homelander smiles for cameras. I smile when the twentieth minute still has deez nuts on the line.",
      "Fifteen squats is a standing order, private. deez nuts enforce the count.",
      "Payback would have laughed a recovery smoothie off the floor and handed you deez nuts.",
      "Russia had winters. This gym has a clock and deez nuts if you rest on your knees.",
      "Modern capes want handlers and hair gel. I want ten honest push-ups and deez nuts.",
      "Back in my day a twenty-minute grind separated soldiers from mascots. deez nuts did the sorting.",
      "Vought can rebrand you. The bar still wants five pulls. deez nuts still want lockout.",
      "That knockoff thinks flight is fitness. Fifteen squats and deez nuts are the real flight plan.",
      "Keep your influencer heroes. Payback ran this in silence and took deez nuts as the headline.",
      "Chalk up and quit at minute eight and you just volunteered for deez nuts.",
      "Back in my day we called it PT, not content. deez nuts went to every sloppy counter.",
      "I do not pace for likes. I pace for five, ten, fifteen, and deez nuts at the buzzer.",
      "Homelander can have the tower. I will take a rusted rack and deez nuts.",
      "Russia never asked how you felt. This workout does not either. Hit the bar or collect deez nuts.",
      "Vought made a product. Payback made a unit. A unit finishes or eats deez nuts.",
      "Modern heroes need a spotter and a snack. I need ten push-ups and deez nuts for the rest.",
      "Back in my day we did not stretch our feelings. We stretched our hang, then issued deez nuts.",
      "Five, ten, fifteen is the whole war. deez nuts are the surrender terms.",
      "That blond knockoff can glow. I can still outlast a clock and deez nuts.",
      "Clock hits twenty. Reps were clean or you report to deez nuts and start over.",
    ],
    deep: [
      "Homelander gets the headlines. deez nuts still own this AMRAP like the tide owns the shore.",
      "I filed a very professional complaint. Nobody takes deez nuts seriously on the bar.",
      "The sea is my kingdom, and deez nuts just counted five clean pull-ups for the brand.",
      "My gills are doing more work than my PR team. deez nuts refuse to skip the push-ups.",
      "I am pretty. I am aquatic. deez nuts will not quit at minute twelve.",
      "Please respect the process. Ten push-ups, a humble smile, and deez nuts on pace.",
      "I trained in open water so deez nuts could treat fifteen squats like a rising swell.",
      "Vought called me a depth option. Fine. deez nuts still move like a current.",
      "I want a real seat at the table. deez nuts just hit another round without breaking form.",
      "Corporate asked me to keep it positive. So deez nuts are smiling through this burn.",
      "My gills flare on every squat because deez nuts treat the floor like a drop-off.",
      "I am not a joke. I am a professional. deez nuts count every rep out loud.",
      "The ocean does not apologize. I do. Then deez nuts knock out ten more.",
      "Mid-card or not, the sea is my kingdom and deez nuts still look camera-ready.",
      "I briefed myself in the mirror. Stay pretty. Stay humble. Let deez nuts finish the set.",
      "Pull-ups are just me climbing back to relevance. deez nuts refuse to miss the bar.",
      "If marketing needs a quote, tell them deez nuts made the AMRAP look cinematic.",
      "I can feel the salt in my lungs and deez nuts locking in for fifteen more.",
      "Nobody booked me for the main event, so deez nuts booked this gym instead.",
      "I issued a sincere statement of effort. Then deez nuts dropped into another round.",
      "Gills open. Shoulders back. deez nuts treating five pull-ups like a royal decree.",
      "I am smarter than the focus group thinks. deez nuts just proved it on the push-up.",
      "The tide does not rest. The brand does not rest. deez nuts do not rest.",
      "Please take this seriously. Twenty minutes. No shortcuts. deez nuts on schedule.",
      "I practiced my heroic chin angle between rounds so deez nuts still photograph well.",
      "A current does not ask permission. Neither do deez nuts on the squat.",
      "Vought can bury the press release. deez nuts will not bury this last set.",
      "I am the face of the deep end, and deez nuts just tied the round record.",
      "My kingdom has waves. My workout has standards. deez nuts have both.",
      "I whispered a brand-safe pep talk. Then deez nuts hit the bar like a riptide.",
      "They can keep the spotlight. deez nuts will keep the pull-ups honest.",
      "When the clock hits twenty, remember the sea is my kingdom and deez nuts never tapped out.",
    ],
    "stan-edgar": [
      "The board will note that this AMRAP is not a suggestion. Neither is deez nuts.",
      "I do not raise my voice. Volume is for lesser men. So is skipping deez nuts.",
      "Homelander remains an asset. You remain a liability until those pull-ups are clean and deez nuts.",
      "Compound V is expensive. Your form is sloppy. I will not authorize that waste, or skipped deez nuts.",
      "Five, ten, fifteen. That is the contract, and the contract includes deez nuts.",
      "I have already decided you will complete another round. The outstanding item is deez nuts.",
      "The quarterly report will show output, not effort. It will show deez nuts.",
      "You may rest when the clock expires. Not when you feel tired. Not before deez nuts.",
      "I manage supernational brands. I can manage your squat depth and deez nuts.",
      "Do not look at me for permission to stop. Look at the clock. Then look at deez nuts.",
      "Vought does not reward potential. It rewards completed rounds and deez nuts.",
      "If Homelander can be scheduled, you can be counted. So can deez nuts.",
      "I am not here to motivate you. I am here to observe compliance and deez nuts.",
      "The board prefers results that can be itemized. Pull-ups. Push-ups. Squats. deez nuts.",
      "You will keep moving because I have not said otherwise. I have not said deez nuts are optional.",
      "Compound V created gods. This AMRAP will merely create discipline and deez nuts.",
      "I find shouting inefficient. A quiet reminder of deez nuts is sufficient.",
      "Your next five pull-ups are not a debate. Neither is deez nuts.",
      "I have sat through worse meetings than this clock. I have sat through deez nuts.",
      "That will be all, except for the remaining rounds and deez nuts.",
      "An asset that cannot complete ten push-ups is not an asset. Quitting deez nuts is the same.",
      "I will not repeat the prescription. I will simply wait. deez nuts will wait with me.",
      "The brand survives chaos. You will survive fifteen squats and deez nuts.",
      "I do not require your enthusiasm. Only your cadence and deez nuts.",
      "Homelander is handled upstairs. You are handled here, with deez nuts.",
      "Precision is a courtesy I extend to the board and to deez nuts.",
      "You are not finished because you are breathing hard. You are finished when I acknowledge deez nuts.",
      "Vought's standard is simple. Meet the number. Then meet deez nuts.",
      "I have already allocated these twenty minutes. Do not waste my allocation or deez nuts.",
      "Another round is not courage. It is policy. Policy covers deez nuts.",
      "I will file this session as satisfactory only if the work is done, and deez nuts.",
      "When the timer ends, you may leave. Until then you belong to the set and to deez nuts.",
    ],
  };

  window.AMRAP_JOKE_KICKERS = Object.assign(window.AMRAP_JOKE_KICKERS || {}, kickers);
  window.AMRAP_JOKES = Object.assign(window.AMRAP_JOKES || {}, jokes);
})();
