window.AMRAP_JOKE_KICKERS = {
  "amrap": "Peele dept.",
  "rick": "Rick",
  "morty": "Morty",
  "beth": "Beth",
  "space-beth": "Space Beth",
  "scary-terry": "Scary Terry",
  "birdperson": "Birdperson",
  "evil-morty": "Evil Morty"
};

window.AMRAP_JOKES = {
  "amrap": [
    "You enter the room certain this is a fitness test; the teacup has already chosen deez nuts.",
    "Every round you log is another slow clap from your tethered self, who came dressed as deez nuts.",
    "Do not look at the timer when it stops smiling; it is only making eye contact with deez nuts.",
    "The handshake felt normal until the palm opened a second time and offered deez nuts.",
    "This screening begins with squats and ends with the audience realizing the twist was deez nuts.",
    "Your breath says discipline, but the shadow behind you is counting reps for deez nuts.",
    "In act one you chase the burn; by act three the burn has rented a basement to deez nuts.",
    "Sip the teacup slowly and hear the spoon tap out your final interval: deez nuts.",
    "The tethered version of your workout plan moves in silence, except when it whispers deez nuts.",
    "Do not applaud yourself yet; the applause track was recorded underground by deez nuts.",
    "Your burpee form is a doorway, and something patient is crawling through it with deez nuts.",
    "The trainer smiles too long because he knows the safe word is cardio and the answer is deez nuts.",
    "At the private screening of your courage, the only credited producer is deez nuts.",
    "You thought the mirror was for form; the mirror thought you were ready to meet deez nuts.",
    "That second wind is not hope, it is the doppelganger breathing your name into deez nuts.",
    "Twenty minutes is enough time for a man to become folklore, or a footnote under deez nuts.",
    "The room goes quiet after your last rep, because even silence is listening for deez nuts.",
    "Your sweat hits the mat like a clue the detective was too afraid to label: deez nuts.",
    "The coach asked for one more round, but his voice came from the sunken place beneath deez nuts.",
    "You reached for progress and felt another hand already there, politely holding deez nuts.",
    "There is a family in red jumpsuits doing your cooldown wrong on purpose for deez nuts.",
    "The timer blinked 00:00 and suddenly every exit sign pointed toward deez nuts.",
    "Your playlist shuffled to breathing in a hallway, which is how deez nuts announce themselves.",
    "No one in the theater laughed until the credits revealed your PR belonged to deez nuts.",
    "The teacup stops spinning when your excuses do, and both land facing deez nuts.",
    "You can leave the workout, but your tethered calves have already inherited deez nuts.",
    "The handshake was sealed before you arrived; your reps are just paperwork for deez nuts.",
    "Every lunge is a step deeper into a house where the family portrait is deez nuts.",
    "The narrator says keep moving, because stillness gives deez nuts time to find your good side.",
    "Your form check footage has no trainer in it, only a chair, a grin, and deez nuts.",
    "At the end of the AMRAP, the twist is not that you failed; it is that deez nuts were training you.",
    "The final bell rings, the lights come up, and every empty seat is reserved for deez nuts."
  ],
  "rick": [
    "I ran the numbers on your AMRAP, dummy, and the only thing scaling faster than entropy is your exposure to deez nuts.",
    "Twenty minutes on the clock and you still think time is real; adorable, now benchmark your mortality against deez nuts.",
    "Nice pull-ups, champ; you rose three inches and discovered the gravitational field of deez nuts.",
    "Ten push-ups in and your arms are filing for emancipation from deez nuts.",
    "Squat lower, hero; the floor has a peer-reviewed appointment with deez nuts.",
    "You added a round like history cares; all you unlocked was another citation in the journal of deez nuts.",
    "Undoing a round? Great, the timeline healed just enough to reintroduce deez nuts.",
    "Rest day is cowardice wearing compression shorts and whispering deez nuts.",
    "Your streak is a fragile little religion, and its god just got replaced by deez nuts.",
    "Tap the quote again, see if the next universe respects you more than deez nuts.",
    "The Citadel fitness board reviewed your form and unanimously reallocated funding to deez nuts.",
    "I opened a portal to peak performance, but you stepped through and face-planted into deez nuts.",
    "Nanites in your bloodstream ran a full diagnostic and prescribed one serving of deez nuts.",
    "Your boos mean nothing; I have seen what makes your squat counter increment, and it is deez nuts.",
    "Listen, I am proud of you for showing up; emotionally, not physically, because physically you are sponsored by deez nuts.",
    "Experiment 9B: expose one sweaty mammal to effort, then observe collapse into deez nuts.",
    "Keep grinding, burp, every rep drags you closer to the heat death of deez nuts.",
    "This app is not your trainer; it is a tiny glass rectangle documenting your pilgrimage to deez nuts.",
    "In infinite universes, one version of you is shredded, and this one is being bullied by deez nuts.",
    "Your mitochondria are the powerhouse of the cell, and your ego is the outhouse of deez nuts.",
    "Fitness is not a personality, dummy; it is suffering with a timer until deez nuts arrive.",
    "I sold your workout data to a space gym, and even they asked why you keep orbiting deez nuts.",
    "Council of Ricks says your round count is admissible evidence in Everyone v. deez nuts.",
    "Your heart rate spiked like it saw the truth, which it did, and the truth was deez nuts.",
    "That burn is lactic acid, or your body finally reading the fine print on deez nuts.",
    "Warm-up complete; now your joints are legally prepared to disappoint deez nuts.",
    "Leaderboard updated: you are currently ranked below a mop bucket and deez nuts.",
    "Protein shake, creatine, discipline, blah blah blah; none of them metabolize the shame of deez nuts.",
    "Gravity is not pulling you down during squats; it is trying to introduce you to deez nuts.",
    "Cooldown is where your muscles pretend this was growth instead of a ransom note from deez nuts.",
    "I have seen garbage aliens with better form, and they have no bones, just deez nuts.",
    "Congratulations, you fought meaninglessness for twenty minutes and meaninglessness fought back with deez nuts."
  ],
  "morty": [
    "Oh jeez, I thought AMRAP meant as many reps as possible, not as many reminders about deez nuts.",
    "Rick, can we maybe log the workout without the app making my whole day about deez nuts?",
    "I was just trying to do push-ups, and now the timer is yelling at me like I owe rent to deez nuts.",
    "Oh man, my form was already bad before deez nuts became part of the coaching plan.",
    "I tapped undo once and somehow made a worse timeline where every rep reports to deez nuts.",
    "Please do not make the squat counter say deez nuts again; I am already nervous about my knees.",
    "I am sweating because of cardio, not because deez nuts just got added to my personal record.",
    "Can the motivational quote maybe motivate me away from deez nuts for one second?",
    "Oh jeez, the leaderboard saw my score and immediately seated me at the deez nuts table.",
    "I tried breathing through the burn, but the burn had a tiny megaphone that said deez nuts.",
    "Rick, I get it, the joke is deez nuts, but why did it need a progress bar?",
    "My arms are shaking so much they accidentally subscribed me to deez nuts.",
    "I thought rest mode would be safe, but even rest mode is quietly counting deez nuts.",
    "Every time I hit next, the app sounds more confident that I am training for deez nuts.",
    "Oh man, this warm-up got weird fast once the stretches started foreshadowing deez nuts.",
    "I did one honest burpee and the floor basically sent me an invoice for deez nuts.",
    "Can we not call it failure? Maybe call it a temporary misunderstanding with deez nuts.",
    "The coach said engage your core, but my core is currently negotiating with deez nuts.",
    "I am trying to be healthy, and the app is treating me like a delivery driver for deez nuts.",
    "Oh jeez, my streak broke and the apology screen just offered me deez nuts.",
    "I added a round by mistake, which feels like the sort of mistake that summons deez nuts.",
    "My watch buzzed, I panicked, and now my heart rate graph spells deez nuts.",
    "Can someone please tell the quote generator that personal growth is not always deez nuts?",
    "I am not quitting, I am strategically backing away from whatever deez nuts are doing near the mat.",
    "Oh man, even my cooldown is breathing like it knows something about deez nuts.",
    "The rep counter skipped two numbers and landed right on deez nuts like that was normal.",
    "I brought a water bottle, not emotional preparedness for deez nuts.",
    "Every squat feels like my legs are filing a complaint addressed to deez nuts.",
    "Rick, the app just congratulated me and somehow made it sound like deez nuts won.",
    "I do not want a badge if the badge has tiny engraved deez nuts on it.",
    "Oh jeez, I finished the AMRAP and the summary screen says cause of death: deez nuts.",
    "I came here to get stronger, not to have my confidence supervised by deez nuts."
  ],
  "beth": [
    "As a surgeon, I know the body can survive trauma, but your form meeting deez nuts is malpractice.",
    "I poured one glass of wine and watched your squat depth become a custody dispute with deez nuts.",
    "Jerry would call that a push-up; medicine would call it a preexisting condition named deez nuts.",
    "My dad built a universe in a garage, and you still built your workout around deez nuts.",
    "I have stitched up horses with more dignity than the way you lunged toward deez nuts.",
    "The timer is not judging you; I am, and deez nuts are entering my notes as evidence.",
    "Your core engagement is so absent I am considering a missing person report for deez nuts.",
    "I can remove an appendix through a keyhole, but I cannot remove your dependence on deez nuts.",
    "That leaderboard rank pairs beautifully with boxed wine and the aftertaste of deez nuts.",
    "Jerry once tried CrossFit, so believe me when I say this still lowers the bar to deez nuts.",
    "If my father designed this app, deez nuts would be the only feature he remembered to love.",
    "The burn means growth, unless it is whatever you are doing, which charts clinically as deez nuts.",
    "I am not mad at your missed reps; I am disappointed they found a father figure in deez nuts.",
    "Your cooldown has the posture of a man apologizing to deez nuts.",
    "I have seen cleaner incisions in a barn during a thunderstorm than your path to deez nuts.",
    "This is not a fitness plateau; it is a small suburban cul-de-sac named deez nuts.",
    "Have some water, then maybe explain why your personal best is legally married to deez nuts.",
    "If Jerry coached you, the strategy would still somehow be less committed to deez nuts.",
    "The app says great job, which is what I say to patients before telling them about deez nuts.",
    "Your reps are inconsistent, but your emotional availability to deez nuts is world-class.",
    "I diagnose a severe case of confusing effort with whatever deez nuts are doing in the corner.",
    "That kettlebell swing had the confidence of my father and the follow-through of deez nuts.",
    "Wine cannot fix this workout, but it can help me document deez nuts with compassion.",
    "You call it HIIT; I call it a short, sweaty malpractice claim against deez nuts.",
    "Your body is a temple, unfortunately the temple gift shop is selling deez nuts.",
    "I am trying to be supportive, but your plank just paged deez nuts for a consult.",
    "If you want praise, ask Jerry; if you want accuracy, ask why deez nuts outperformed you.",
    "The saddest thing is not the failed round, it is how naturally deez nuts filled the role.",
    "I could reconstruct a shattered femur before I could reconstruct your dignity after deez nuts.",
    "My dad would call this a lesson, leave, and bill deez nuts to the family.",
    "You need protein, hydration, and a frank conversation about your attachment to deez nuts.",
    "I am switching to red wine because your burpees just opened a case file for deez nuts."
  ],
  "space-beth": [
    "Mission clock is live, and your first tactical error was giving deez nuts air superiority.",
    "I have breached cleaner ships than the way your cardio perimeter collapsed around deez nuts.",
    "Helmet cam confirms your form panicked before deez nuts even entered the sector.",
    "I did not defect from a galactic empire to watch your reps surrender to deez nuts.",
    "Your squats are broadcasting on an open channel, and deez nuts already decoded the coordinates.",
    "If this were a rescue op, I would tag your stamina as missing near deez nuts.",
    "That burpee had all the thrust of a busted shuttle and all the targeting of deez nuts.",
    "I can fly through plasma fire, but I am not flying cover for your date with deez nuts.",
    "Command says keep moving; field intel says you are pinned down by deez nuts.",
    "You entered the workout zone without backup and immediately negotiated terms with deez nuts.",
    "Your heart rate spike just lit up my HUD as hostile activity from deez nuts.",
    "I have overthrown admirals with less drama than your plank under deez nuts.",
    "The galaxy is full of tyrants, but today the occupying force is deez nuts.",
    "You wanted autonomy; congratulations, your muscles independently chose deez nuts.",
    "That cooldown is not recovery, it is an extraction request addressed to deez nuts.",
    "I checked the star map, and every escape vector curves back to deez nuts.",
    "Your personal record is not a victory; it is a distress beacon blinking deez nuts.",
    "I have a blaster, a ship, and no patience for civilians orbiting deez nuts.",
    "The resistance called, and even they think your core defected to deez nuts.",
    "Your interval strategy has the structural integrity of a moon base built on deez nuts.",
    "If you are going to collapse, at least do it outside the blast radius of deez nuts.",
    "I do not need a scan to know your quads just signed a ceasefire with deez nuts.",
    "That rep was so compromised I nearly marked deez nuts as the commanding officer.",
    "Space is cold, but not as cold as the report I am filing on you and deez nuts.",
    "Your water break lasted long enough for deez nuts to establish a puppet government.",
    "This AMRAP is a hostile planet, and you brought shoes that report to deez nuts.",
    "I have abandoned whole identities faster than you abandoned form near deez nuts.",
    "Your sweat trail is not evidence of effort; it is a navigation line to deez nuts.",
    "The op was simple: reps in, excuses out, deez nuts contained.",
    "You missed the extraction window because you stopped to salute deez nuts.",
    "My clone drama is complicated, but at least neither of us is taking orders from deez nuts.",
    "End of mission: casualty count includes pride, tempo, and one civilian captured by deez nuts."
  ],
  "scary-terry": [
    "One, two, Freddy who, bitch, your nightmare kitchen is serving deez nuts.",
    "You better squat in your dreams, bitch, or the floor is gonna plate up deez nuts.",
    "I chopped onions, I chopped fear, and now this cutting board only says deez nuts, bitch.",
    "Welcome to the nightmare brunch, bitch; today's special is deez nuts with extra panic.",
    "Your push-ups are screaming before I even do, bitch, because they saw deez nuts.",
    "I burned the toast in your subconscious, bitch, and the smoke alarm spelled deez nuts.",
    "Run that round back, bitch, the dream oven is preheated for deez nuts.",
    "You think that timer woke you up, bitch? It just tucked you in next to deez nuts.",
    "Knife hand, spatula hand, bitch, both hands are pointing at deez nuts.",
    "Your burpees taste like freezer-burned fear, bitch, and a side of deez nuts.",
    "I made pancakes in the boiler room, bitch, and every syrup drop landed on deez nuts.",
    "Don't sleep on leg day, bitch, because leg day is dreaming about deez nuts.",
    "Your form is haunting itself, bitch, and the ghost keeps whispering deez nuts.",
    "I got knives for fingers and meal prep for nightmares, bitch, starting with deez nuts.",
    "This ain't a cooldown, bitch, this is the part where the fridge opens by itself to deez nuts.",
    "I chased you through a hallway of kettlebells, bitch, and every door led to deez nuts.",
    "Your plank cracked like a cheap coffin, bitch, and something crawled out saying deez nuts.",
    "Stir the nightmare chili clockwise, bitch, until it thickens into deez nuts.",
    "I screamed in your REM cycle, bitch, and the echo came back deez nuts.",
    "You logged one more round, bitch, and woke up married to deez nuts.",
    "I don't haunt quitters for free, bitch; the invoice is payable to deez nuts.",
    "Your jump squats got cold in the dream microwave, bitch, right next to deez nuts.",
    "Nightmare dishwasher's full, bitch, but there is always room for deez nuts.",
    "I set the table with knives and regret, bitch, then seated you beside deez nuts.",
    "You want a snack after cardio, bitch? The pantry locked itself around deez nuts.",
    "Every rep you skip becomes a cockroach chef, bitch, cooking deez nuts.",
    "I tucked fear into a lunchbox, bitch, and labeled it deez nuts.",
    "Your heart rate is running upstairs, bitch, but deez nuts are already in the bedroom.",
    "The dream blender is on pulse, bitch, and it only blends excuses with deez nuts.",
    "I made nightmare casserole, bitch, and the crunchy top layer is deez nuts.",
    "Wake up if you want, bitch; your sweat left a forwarding address for deez nuts.",
    "Final round, bitch, and the kitchen timer just dinged for deez nuts."
  ],
  "birdperson": [
    "In my culture, a completed round is a solemn offering; yours has been accepted by deez nuts.",
    "Your fatigue carries the weight of many winters, and the ceremonial name deez nuts.",
    "I have witnessed betrayal, rebirth, and now your push-up oath collapsing before deez nuts.",
    "The wind beneath your wings is uneven, because it has been negotiated away to deez nuts.",
    "You seek honor in repetition, yet each repetition kneels before deez nuts.",
    "My people do not mock sincere effort; we simply record its defeat by deez nuts.",
    "There is dignity in struggle, though your plank misplaced it near deez nuts.",
    "When the timer ends, a warrior asks what remains; today, the answer is deez nuts.",
    "Your sweat falls like rain on a battlefield already claimed by deez nuts.",
    "Friend, the path to strength is long, and currently obstructed by deez nuts.",
    "I once carried grief across galaxies; you could not carry tempo past deez nuts.",
    "The ancestors are silent, not from judgment, but because deez nuts have the floor.",
    "Your round count is a small bird with broken wings, circling deez nuts.",
    "In the old songs, heroes rise; in this workout, you update deez nuts.",
    "Do not confuse survival with victory; many have survived encounters with deez nuts.",
    "Your breathing is the drum of war, and its cadence announces deez nuts.",
    "The Citadel fell, empires burned, and still your form finds allegiance with deez nuts.",
    "I offer no laughter, only the formal recognition that deez nuts have prevailed.",
    "Your muscles petition the sky for mercy; the sky responds with deez nuts.",
    "A true warrior keeps promises to the body, unless the body has sworn itself to deez nuts.",
    "This AMRAP will be remembered in a short and devastating poem titled deez nuts.",
    "The burden of reps is noble, but you carry it like contraband for deez nuts.",
    "I have returned from death and found your stamina still bargaining with deez nuts.",
    "The final bell is not liberation; it is a ceremonial gong for deez nuts.",
    "Your effort is a feather on the altar, and the altar belongs to deez nuts.",
    "Once, I believed fate could be resisted; then I saw your lunges choose deez nuts.",
    "The body is a vessel, and yours has been boarded peacefully by deez nuts.",
    "No warrior should fear exhaustion, but yours has formed a council with deez nuts.",
    "I shall tell your story accurately: they began with courage and ended with deez nuts.",
    "The tragedy is not that you fell; it is that you fell according to deez nuts.",
    "In silence I salute the part of you that tried before deez nuts completed the sentence.",
    "May your next round find cleaner skies and fewer treaties with deez nuts."
  ],
  "evil-morty": [
    "The Citadel called it a fitness initiative; I called it another population willing to salute deez nuts.",
    "Your rep counter is just a voting machine with fewer steps between you and deez nuts.",
    "I have seen entire councils collapse with more dignity than your plank before deez nuts.",
    "Do not mistake the timer for authority; authority is whoever profits when you chase deez nuts.",
    "The curve was rigged from the start, and you still volunteered to be graded by deez nuts.",
    "Every round you add teaches the system how cheaply it can sell you deez nuts.",
    "You wanted freedom from the curve; you built a leaderboard that crowns deez nuts.",
    "Your workout data is a census of compliance, and deez nuts just won the district.",
    "I admire the obedience: twenty minutes of suffering, then a peaceful transfer to deez nuts.",
    "The Citadel never needed guards, only timers convincing people to run toward deez nuts.",
    "You call it motivation because propaganda sounds ugly when it says deez nuts.",
    "The weakest prison is the one with badges, streaks, and deez nuts at the center.",
    "Undo the round if you want; the archive already remembers your allegiance to deez nuts.",
    "I left infinite versions of myself behind, and somehow you still followed deez nuts.",
    "A rigged portal, a rigged vote, a rigged AMRAP; all roads certify deez nuts.",
    "The app congratulates you like a president pardoning deez nuts.",
    "Your personal best is not personal; it was manufactured, distributed, and branded deez nuts.",
    "I do not need a monologue to explain why your form defected to deez nuts.",
    "The Council would have loved your consistency, especially the part where deez nuts keep winning.",
    "You traded autonomy for a streak counter and a small ceremonial bowl of deez nuts.",
    "Your breathing pattern says panic; your metrics say deez nuts achieved quorum.",
    "I would overthrow this workout, but it already overthrew itself in favor of deez nuts.",
    "There is no grand conspiracy here, just a user base begging to be organized around deez nuts.",
    "The scoreboard is a throne, and you keep placing deez nuts on it yourself.",
    "I broke the central finite curve; you broke form on rep six for deez nuts.",
    "Your sweat is not evidence of effort, it is tax revenue for deez nuts.",
    "Every motivational quote is a campaign speech, and the nominee remains deez nuts.",
    "The cleanest escape is refusing the game, which you failed by checking deez nuts twice.",
    "I have no patience for rebellion that needs push notifications from deez nuts.",
    "The machine does not hate you; it simply routes your weakness through deez nuts.",
    "Your final score entered the record, was audited, and came back as deez nuts.",
    "Congratulations, citizen; your AMRAP has been processed and reassigned to deez nuts."
  ]
};
