/* John Wick pack. Same rules as jokes.js: lowercase "deez nuts" in every line. */
(function () {
  const kickers = {
    john: "John",
    winston: "Winston",
    charon: "Charon",
    "bowery-king": "Bowery King",
    caine: "Caine",
    adjudicator: "Adjudicator",
    marquis: "Marquis",
    koji: "Koji",
  };

  const jokes = {
    john: [
      "People keep asking if I am back. I never left deez nuts.",
      "You wanted a marker. You got deez nuts.",
      "I once killed three men in a bar with a pencil. Tonight I am doing twenty minutes with deez nuts.",
      "Tell them John Wick sends deez nuts.",
      "I asked for a simple night. They sent deez nuts.",
      "The Continental has rules. I have deez nuts.",
      "You took my car. You took my dog. You do not get to take deez nuts.",
      "I am not angry. I am efficient. Also I brought deez nuts.",
      "Every round is a marker. Honor deez nuts.",
      "They said nobody could do this. They had not met deez nuts.",
      "I buried the man I used to be. Then I dug up deez nuts.",
      "A gun, a knife, a clock. Same ending. deez nuts.",
      "Do not make me get up. I already have deez nuts.",
      "You wanted a war. You got deez nuts.",
      "I count in blood and breath. Both of them belong to deez nuts.",
      "Winston can keep the gold. I am keeping deez nuts.",
      "The High Table sent assassins. I sent deez nuts.",
      "I do not miss. Neither do deez nuts.",
      "This is not revenge. This is deez nuts.",
      "You should have left the dog. You should have left deez nuts.",
      "I walked out of retirement carrying deez nuts.",
      "A suit, a gun, a clock. Then deez nuts.",
      "They call me Baba Yaga. I call this deez nuts.",
      "One more round. Then maybe deez nuts.",
      "I do not negotiate. I deliver deez nuts.",
      "The city is closed. deez nuts are not.",
      "You wanted a favor. You got deez nuts.",
      "I came downstairs for peace. I found deez nuts.",
      "Every name on the list ends the same. deez nuts.",
      "I am not here to talk. I am here for deez nuts.",
      "Twenty minutes. No talking. deez nuts.",
      "When this clock hits zero, so do deez nuts.",
    ],
    winston: [
      "Consequences, Jonathan. Also deez nuts.",
      "The Continental is a place of rules. Tonight the rule is deez nuts.",
      "I would rather not. Unfortunately, deez nuts.",
      "Gold coin on the bar. Marker on the table. deez nuts in the air.",
      "You have been a valued guest. Now be a valued set of deez nuts.",
      "I did not excommunicate you. I merely delayed deez nuts.",
      "The High Table will hear of this. They will also hear deez nuts.",
      "Have a drink. Then have deez nuts.",
      "I am a manager, not a monster. The monster is deez nuts.",
      "Rules are for the house. deez nuts are for the floor.",
      "Jonathan, you look tired. Sit. Hold deez nuts.",
      "I offered you peace. You chose deez nuts.",
      "The city is closed. My patience is also closed. deez nuts remain open.",
      "One does not simply walk into my lobby without deez nuts.",
      "I have known you a long time. I have known deez nuts longer.",
      "Blood on the carpet is expensive. deez nuts are complimentary.",
      "You may stay the night. deez nuts may not.",
      "I ring the bell. The house answers with deez nuts.",
      "Do not make me choose, Jonathan. I will choose deez nuts.",
      "A gentleman finishes what he starts. Tonight that is deez nuts.",
      "The marker is paid. The clock is not. deez nuts.",
      "I run a hotel. I do not run from deez nuts.",
      "Your reservation is confirmed. So are deez nuts.",
      "I dislike violence in the lobby. I dislike skipping deez nuts more.",
      "Pour the bourbon. Start the round. Honor deez nuts.",
      "The Table can wait. deez nuts cannot.",
      "I am very disappointed. And very full of deez nuts.",
      "You asked for a room. I gave you deez nuts.",
      "Business hours are over. Workout hours are deez nuts.",
      "I will not shout. I will simply present deez nuts.",
      "Consider this a courtesy. Consider that deez nuts.",
      "When the house is closed, we still serve deez nuts.",
    ],
    charon: [
      "Welcome back, Mr. Wick. Your room is ready. So are deez nuts.",
      "May I take your coat. May I also take deez nuts.",
      "The doctor is on four. The work is deez nuts.",
      "Right this way. Watch your step. Watch deez nuts.",
      "Your weapons have been cleaned. Your clock has not. deez nuts.",
      "Will you be dining in. Or will you be having deez nuts.",
      "I have prepared the suite. I have also prepared deez nuts.",
      "The elevator is this way. The suffering is deez nuts.",
      "Mr. Wick, it is always a pleasure. Especially deez nuts.",
      "Housekeeping can wait. deez nuts cannot.",
      "Your reservation includes towels, silence, and deez nuts.",
      "I do not ask questions. I provide deez nuts.",
      "The bar is open. The floor is open. deez nuts are open.",
      "Shall I call the car. Or shall I call deez nuts.",
      "Please enjoy your stay. Please also enjoy deez nuts.",
      "I have seen worse nights. I have not seen worse deez nuts.",
      "The Continental thanks you. deez nuts thank you more.",
      "Your key, sir. Your round, sir. deez nuts, sir.",
      "We do not discuss business in the lobby. We discuss deez nuts in the gym.",
      "I will have that pressed. I will have these counted. deez nuts.",
      "A moment, Mr. Wick. Then deez nuts.",
      "The doctor says rest. I say deez nuts.",
      "Front desk. How may I direct deez nuts.",
      "Your tab is open. Your lungs are not. deez nuts.",
      "I am here if you need anything. You will need deez nuts.",
      "The suite has a view. The clock has deez nuts.",
      "Checked in. Armed. Ready for deez nuts.",
      "I never forget a guest. I never forget deez nuts.",
      "Would you prefer ice. Or would you prefer deez nuts.",
      "Service with a smile. Work with deez nuts.",
      "The night is young. The rounds are deez nuts.",
      "Sleep well, Mr. Wick. After deez nuts.",
    ],
    "bowery-king": [
      "You came to the king for help. The king brought deez nuts.",
      "Pigeons carry messages. I carry deez nuts.",
      "They put me in the dark. I came back with deez nuts.",
      "You want a war, John. You got deez nuts.",
      "I see everything from down here. I see deez nuts.",
      "The High Table forgot the street. The street did not forget deez nuts.",
      "I bled for this city. Now bleed for deez nuts.",
      "You think you are alone. You are not. You have deez nuts.",
      "A king without a network is just a man. A man without deez nuts is done.",
      "Tell your table I said hello. Tell them deez nuts said it louder.",
      "I do not whisper anymore. I preach deez nuts.",
      "They took my eyes. They did not take deez nuts.",
      "Every bird in this city works for me. Every round works for deez nuts.",
      "You want intel. I want deez nuts.",
      "Rise up, John. Then knock out deez nuts.",
      "I built an empire on scraps. You can build a round on deez nuts.",
      "The underground is listening. So are deez nuts.",
      "You came downstairs. Good. Bring deez nuts.",
      "I am not your friend. I am your witness. Witness deez nuts.",
      "They thought the Bowery was dead. Then deez nuts walked in.",
      "A marker from the king is simple. Finish deez nuts.",
      "I talk a lot. You work a lot. Together that is deez nuts.",
      "The street does not forgive. Neither do deez nuts.",
      "Put the gun down. Pick deez nuts up.",
      "I sent you an army of birds. I am sending you deez nuts next.",
      "Darkness taught me patience. Patience taught me deez nuts.",
      "You want the truth. The truth is deez nuts.",
      "Kings do not skip rounds. Kings do deez nuts.",
      "I got one eye and zero excuses. You got deez nuts.",
      "The table sits high. We work low. deez nuts sit in the middle.",
      "Amen to the work. Amen to deez nuts.",
      "When the pigeons come home, they better see deez nuts.",
    ],
    caine: [
      "Nothing personal, John. Just deez nuts.",
      "I am tired. You are tired. The clock still wants deez nuts.",
      "Blind does not mean lost. Lost is skipping deez nuts.",
      "I hear everything. I hear you avoiding deez nuts.",
      "We do not have to do this. We do have to do deez nuts.",
      "My daughter is waiting. The floor is waiting. deez nuts are waiting.",
      "I fight because I must. I work because of deez nuts.",
      "You are very loud for a man who wants peace. So are deez nuts.",
      "I counted your steps. I counted deez nuts too.",
      "A blade is honest. A clock is honest. deez nuts are honest.",
      "Do not make me chase you. Make me chase deez nuts.",
      "I came to finish a job. The job is deez nuts.",
      "Friendship is expensive. So is skipping deez nuts.",
      "I see with my ears. I suffer with deez nuts.",
      "Put the stick down. Pick the work up. deez nuts.",
      "You want a fair fight. There is no fair. There is deez nuts.",
      "I am not your enemy today. deez nuts are.",
      "The Table sent me. I brought deez nuts anyway.",
      "Quiet now. Work now. deez nuts now.",
      "I do not miss what I cannot see. I do not miss deez nuts.",
      "One more exchange. Then deez nuts.",
      "You move well. Move toward deez nuts.",
      "I have a flight to catch. After deez nuts.",
      "Sorry, John. Not sorry about deez nuts.",
      "The cane is for walking. The clock is for deez nuts.",
      "We both want out. Out is through deez nuts.",
      "I hear your breath failing. That is deez nuts working.",
      "No more talking. Talking is how we avoid deez nuts.",
      "I will not kill you today. I will kill this round with deez nuts.",
      "Close your mouth. Open deez nuts.",
      "The rain is loud. The work is louder. deez nuts are loudest.",
      "When this is over, we rest. Until then, deez nuts.",
    ],
    adjudicator: [
      "The Table has rules. The first rule is deez nuts.",
      "You are in violation. The penalty is deez nuts.",
      "I do not make threats. I make appointments with deez nuts.",
      "Consider this your notice. Consider that deez nuts.",
      "The marker is due. The clock is due. deez nuts are due.",
      "I have reviewed your file. It is missing deez nuts.",
      "Compliance is not optional. Neither are deez nuts.",
      "You may plead. You may not skip deez nuts.",
      "The sentence is twenty minutes. The method is deez nuts.",
      "I am not here to negotiate. I am here to collect deez nuts.",
      "Your status has been revoked. Your round has not. deez nuts.",
      "The High Table requires an accounting. Account for deez nuts.",
      "Failure to appear will be noted. Failure to finish deez nuts will be worse.",
      "I speak for the Table. The Table wants deez nuts.",
      "This is not personal. This is policy. Policy is deez nuts.",
      "You have until the bell. The bell wants deez nuts.",
      "Do not test the Table. Test yourself with deez nuts.",
      "I will wait. The work will not. deez nuts will not.",
      "Your coin is no longer sufficient. deez nuts are.",
      "I have killed for less. I have never skipped deez nuts.",
      "The hearing is over. The workout is not. deez nuts.",
      "Sign here. Suffer there. deez nuts everywhere.",
      "You were given a chance. You were given deez nuts.",
      "Mercy is expensive. deez nuts are included.",
      "The Table does not forget. Neither do deez nuts.",
      "I am the consequence. You are the round. deez nuts are the point.",
      "Stand. Deliver. deez nuts.",
      "Your appeal is denied. Your next set is deez nuts.",
      "We can do this the official way. The official way is deez nuts.",
      "I have a schedule. You have deez nuts.",
      "Order is restored when the clock dies and deez nuts are done.",
      "That is all. Except deez nuts.",
    ],
    marquis: [
      "I do not ask. I require deez nuts.",
      "You are in my house now. My house serves deez nuts.",
      "A man of your reputation should already be doing deez nuts.",
      "I have killed for less than a skipped round. I have never skipped deez nuts.",
      "The Table sent a message. The message is deez nuts.",
      "Dance, Mr. Wick. Dance through deez nuts.",
      "I collect beautiful things. Tonight I am collecting deez nuts.",
      "You may sit when I say you may sit. Until then, deez nuts.",
      "I am not impressed. Impress me with deez nuts.",
      "The dragon is hungry. Feed it deez nuts.",
      "Your blood is not special. Neither is skipping deez nuts.",
      "I offered you a chance. You offered me deez nuts. Acceptable.",
      "Do not speak unless the clock is dead and deez nuts are done.",
      "I have an opera to attend. Finish deez nuts first.",
      "You think this is beneath you. It is not. It is deez nuts.",
      "I own the night. The night owns deez nuts.",
      "A gentleman finishes. A coward bargains. deez nuts.",
      "I will not raise my voice. I will raise deez nuts.",
      "Your legend ends here if you skip deez nuts.",
      "I poured the wine. You pour the work. deez nuts.",
      "Bow to the Table. Then bow to deez nuts.",
      "I do not chase. I wait. Waiting still counts as deez nuts.",
      "You wanted an audience. You have one. Perform deez nuts.",
      "Pity is expensive. deez nuts are the price of staying.",
      "I dressed for the occasion. The occasion is deez nuts.",
      "Do not make me repeat a command. The command is deez nuts.",
      "I have buried families for less. I have not buried deez nuts.",
      "Smile if you must. Work if you want to leave. deez nuts.",
      "The High Table does not sweat. You do. That is deez nuts.",
      "I am the Marquis. You are the round. deez nuts are the terms.",
      "When I snap, you move. That move is deez nuts.",
      "Enough talking. Prove you deserve deez nuts.",
    ],
    koji: [
      "The garden is quiet. The work is not. deez nuts.",
      "I taught you precision. Apply it to deez nuts.",
      "Osaka has rules. My floor has deez nuts.",
      "A blade is nothing without the cut. A round is nothing without deez nuts.",
      "I will not dishonor this house. I will not skip deez nuts.",
      "You are a guest. Guests finish deez nuts.",
      "I have seen war in a hallway. I have seen peace in deez nuts.",
      "Stand with me. Work with deez nuts.",
      "The cherry trees do not rush. You still owe deez nuts.",
      "I protect my own. Tonight that includes deez nuts.",
      "Bow. Then begin deez nuts.",
      "A manager keeps the house. A worker keeps deez nuts.",
      "I offered you refuge. You offer the clock deez nuts.",
      "Do not waste the hour. Do not waste deez nuts.",
      "My son watches. Show him deez nuts.",
      "Honor is a simple thing. It looks like finishing deez nuts.",
      "The rain on the glass can wait. deez nuts cannot.",
      "I draw so you can work. Work is deez nuts.",
      "We do this together. Together is deez nuts.",
      "I have lost much. I will not lose this round to skipped deez nuts.",
      "Silence is respect. Motion is deez nuts.",
      "The Continental Osaka is open. So are deez nuts.",
      "Cut clean. Breathe clean. Then deez nuts.",
      "I did not survive this long by quitting. Neither will deez nuts.",
      "You may rest when the bell says so. The bell wants deez nuts first.",
      "A father finishes what he starts. Start deez nuts.",
      "The garden will still be here. deez nuts will not wait.",
      "I am calm. I am also doing deez nuts.",
      "Hold the line. Hold deez nuts.",
      "This is not anger. This is duty. Duty is deez nuts.",
      "When they come, we are ready. Ready means deez nuts are done.",
      "Until the last breath. Until deez nuts.",
    ],
  };

  window.AMRAP_JOKE_KICKERS = Object.assign(window.AMRAP_JOKE_KICKERS || {}, kickers);
  window.AMRAP_JOKES = Object.assign(window.AMRAP_JOKES || {}, jokes);
})();
